export const projects = [
  {
    id: 1,
    type: "android",
    title: "CodeRespite: Refresh Your Tech Skills",
    techStack: "React Native, Firebase, AsyncStorage, JavaScript",
    description:
      "A self-paced mobile learning app covering HTML, CSS,JavaScript, Node.js, React, and React Native. Features include reading lessons, quiz modules, progress tracking.",
    image: "coderespite",
    live: "https://play.google.com/store/apps/details?id=com.mindcraftlearning.coderespite",

    github: "https://github.com/amit265/coderespite",
  },
  {
    id: 2,
    type: "android",
    title: "Trivia Quest AI: Fun Quiz Game",
    techStack:
      "React Native, OpenAI API, JavaScript, AsyncStorage, Firebase Auth",
    description:
      "An AI-powered quiz app where users answer dynamic questions generated by OpenAI. Offers real-time feedback and explanations to enhance learning.",
    image: "trivia",
    live: "https://play.google.com/store/apps/details?id=com.coderespite.triviaquestai",

    github: "https://github.com/amit265/trivia-quest-ai",
  },
  {
    id: 3,
    type: "android",
    title: "Spin the Wheel : Pick for me",
    techStack: "React Native, JavaScript",
    description:
      "A utility app to create customizable spin wheels for random choices - ideal for games, raffles, and quick decisions. Lightweight and responsive for all screen sizes.",
    image: "spinthewheel",
    live: "https://play.google.com/store/apps/details?id=com.mindcraftlearning.spinthewheel",
    github: "https://github.com/amit265/spin-the-wheel",
  },
  {
    id: 4,
    type: "web",
    title: "Netflix GPT",
    techStack:
      "React, Redux, React Router DOM, Firebase Authentication, TMDB API, OpenAI API, Tailwind CSS",
    description:
      "A movie recommendation platform that uses TMDB API for search/browse and integrates OpenAI for personalized suggestions. Includes secure login, movie detail pages, and a dynamic UI.",
    image: "netflixgpt",
    live: "",
    github: "https://github.com/amit265/React-Projects/tree/main/netflixgpt",
  },
  {
    id: 5,
    type: "web",
    title: "Swiggy Clone App",
    techStack: "React, Redux, React Router DOM, Custom Hooks, Swiggy API",
    description:
      "This is a Swiggy Clone app built with React. It lists restaurants using the Swiggy API, allows you to view restaurant details and menus, and lets you add food items to a cart, place orders, and view success messages.",
    image: "swiggy",
    live: "",
    github: "https://github.com/amit265/React-Projects/tree/main/swiggy",
  },
];
